### PR TITLE
Data cci c3s

### PR DESCRIPTION
**Pull request by wpreimes**
Adding 7 new c3s and cci versions (already on qa4sms1)

### CODE REVIEW

**Comment by sheenaze** [comment]
I thought we agreed to point to a particular package version in our env :)

**Comment by wpreimes** [comment]
I dont think so, we said we shouldnt point to a branch ;)

**Comment by wpreimes** [comment]
anyway, I plan to release the esa cci package, if you want you can wait a few hours and I will update the link in the environment file

**Comment by sheenaze** [comment]
I will. I'm working on a contact form now and I should be able to finish it today.

**Comment by sheenaze** [comment]
But I'll merge this one and push it to the test, so you can already test it.

**Comment by wpreimes** [comment]
@sheenaze one of the tests failed though

**Comment by sheenaze** [comment]
I noticed. But I deployed already to the test instance so we can check how it behaves when using real data.

**Comment by wpreimes** [comment]
#686 should fix it

**Pull request merged**
