### PR TITLE
MTR updates towards release 1

### PR DESCRIPTION
**Pull request by pstradio**
Collect the updates relative to the SMOS L3 validation exercise as requested from MTR

- [x] method for adapting the timestamps to the exact overpass time in pytesmo
- [x] Include method for adapting the timestamps to the exact overpass time
- [x] Update environment with new pytesmo release
- [x] Apply temporal matching window selection
- [x] Update test data
- [x] Correct method for RFI filtering to include RFI_Ratio
- [x] Fix tests

### CODE REVIEW

**Comment by sheenaze** [comment]
Did you apply migration locally?

**Comment by pstradio** [comment]
> Did you apply migration locally?

Yes, I did - successfully

**Comment by sheenaze** [comment]
Give me few minutes

**Comment by sheenaze** [comment]
I just opened a PR to your branch with a fix :)

**Comment by sheenaze** [comment]
Does everything work now?

**Comment by wpreimes** [comment]
keep in mind that it is more important to update https://github.com/awst-austria/qa4sm/blob/master/environment/create_conda_env.sh than the environment.yml file (which should be generated from the .sh script)

I would e.g. force pytesmo>=0.14,0 here https://github.com/pstradio/qa4sm/blob/MTR_review/environment/create_conda_env.sh#L100 to make sure that the correct version is always added to the env yml.

**Comment by sheenaze** [comment]
@wpreimes what would we do without you ;)
but seriously, since it is going to be a pretty big release, I'm planning on updating all the packages anyway and I'll also take a look on the create_conda file to see what kind of restrictions we need to put there.

**Comment by sheenaze** [comment]
btw... the validation comparison module is a very useful tool for verifying new validation settings :D

**Comment by sheenaze** [comment]
Screenshot from 2022-05-16 13-53-52
this is a comparison of two validations done locally, one is done with 6 hour temporal matching window and the second one with 20. Do the differences look good?

**Comment by wpreimes** [comment]
It makes sense that they don't differ too much (although the differences are very small). It makes sense that the RSS is higher for a larger window (although I would expect a factor of 3?). The nobs should also differ by a factor of ~3.

maybe make one with a 1H and one with 6H window

**Review by sheenaze — APPROVED** [review]
If the differences in the screen shot I posted look ok, then it seems to be ok, I'll deploy changes to the first instance in the first place anyway, so there still will be some time to test it.

**Comment by pstradio** [comment]
> It makes sense that they don't differ too much (although the differences are very small). It makes sense that the RSS is higher for a larger window (although I would expect a factor of 3?). The nobs should also differ by a factor of ~3.
> 
> maybe make one with a 1H and one with 6H window
> 
> Can it be that the max. temp window is 12? @pstradio

You mean, whether the parameter of the pytesmo function has a max?

**Comment by sheenaze** [comment]
Maybe we should just deploy changes to the test instance and then test them? And not rely only on my local validations.

**Comment by pstradio** [comment]
Yes ok, go ahead and deploy please

**Comment by sheenaze** [comment]
Has the qa4sm-reader been updated?

**Comment by pstradio** [comment]
Not yet, but it doesn't matter for now - I will just make a separate PR with the fixes

**Pull request merged**
