### PR TITLE
Change reader for new SMOS L2 Format and add overpass filter

### PR DESCRIPTION
**Pull request by wpreimes**
Testdata updated for new SMOS L2 Format
Data transferred to server (but not replaced old data yet)

We have to coordinate when we deploy this, so we can change the path on the server

### CODE REVIEW

**Comment by sheenaze** [comment]
@wpreimes should I merge it today and deploy it before the workshop?

**Comment by sheenaze** [comment]
@wpreimes changes are already on the test.

**Comment by wpreimes** [comment]
It won‘t work on test unless we change the data folder name, which would break Smos L2 you on prod.

**Comment by sheenaze** [comment]
Ah, yeah, I forgot. Ok. I'll update the paths.

**Pull request merged**
