### PR TITLE
Use time stamp adapter to compute exact time

### PR DESCRIPTION
**Pull request by wpreimes**
Fixing differences in exact time stamp of the SBPCA data leading to failing temp. matching in some locations when choosing a 1H window (time differences were up to 40 minutes).

### CODE REVIEW

**Comment by wpreimes** [comment]
old
image
new
image

**Comment by wpreimes** [comment]
@sheenaze please include this fix next time you deploy a new version to prod.

**Comment by wpreimes** [comment]
It's a fix, so rather urgent. If there are more things in the pipeline for a release in the next e.g. 10 days you can wait, otherwise release it as soon as possible please.

**Comment by sheenaze** [comment]
I mean, I wanted to the deploy the new layout, but it may take more time than expected. I'll deploy it on Monday.

**Pull request merged**
