### PR TITLE
Fix smosl2 data loss issue

### PR DESCRIPTION
**Pull request by wpreimes**
Fix for the issue (currently on test) where SMOS L2 reading loses data.

### CODE REVIEW

**Comment by wpreimes** [comment]
@sheenaze this can be merged and deployed from my side. Keep in mind that test and prod currently point to different versions of SMOS L2

**Comment by sheenaze** [comment]
I keep it in mind, I'm just not sure what I should do about it.

**Comment by wpreimes** [comment]
if you deploy this to test next, do whatever you did before to make it work on prod and test at the same time (I think manually changing the path on test)
if you deploy to prod next, make sure that we use the data in SMOS_L2_v700_new_format (rename directory).

**Comment by sheenaze** [comment]
Ok.

**Pull request merged**
