### PR TITLE
Frm4sm release2 data upload file requirements

### PR DESCRIPTION
**Pull request by wpreimes**

### CODE REVIEW

**Comment by wpreimes** [comment]
@sheenaze Maybe on the help page, you can add a few lines on the GUI of the data upload (i.e. click 'select file', then upload etc.) and there you can refer to the page that describes the data format requirements.

**Comment by sheenaze** [comment]
Yeah, makes sense. I'll update it and the push everything to the frm4sm branch.

**Comment by sheenaze** [comment]
@wpreimes,  can I make some styling improvements to the text you added?

**Comment by wpreimes** [comment]
Yes please I was in a hurry 😅

**Comment by sheenaze** [comment]
I'll try to finish it today so on Monday we are ready with the test instance.

**Comment by sheenaze** [comment]
Screenshot from 2023-01-27 20-46-31
is the table ok?

**Pull request merged**
