### PR TITLE
Smos sbpca

### PR DESCRIPTION
**Pull request by wpreimes**

### CODE REVIEW

**Comment by sheenaze** [comment]
@wpreimes please remember about assigning the proper user to the non-public dataset, 'user: 1'.

**Comment by sheenaze** [comment]
thanks :)

**Comment by sheenaze** [comment]
@wpreimes  zenodo sandbox doesn't work, so your check may fail. Just ignore it.

**Comment by wpreimes** [comment]
can be merged and deployed now from my side

**Comment by sheenaze** [comment]
Ok, I'm merging it and deploying

**Pull request merged**
