### PR TITLE
Add wrapper to extend time series with new data from airflow

### PR DESCRIPTION
**Pull request by wpreimes**
tests will probably fail. I will fix them. For the automatic dataset extension this should be everything that we have to change in the webservice. This is just to show that you don't have to wait for my changes to test deploy the other updates

### CODE REVIEW

**Comment by sheenaze** [comment]
I can take a look at tests on Monday, unless you know what's wrong there.

**Comment by wpreimes** [comment]
I know whats wrong

On 18.10.2024, at 19:24, Monika Tercjak ***@***.***> wrote:

﻿

I can take a look at tests on Monday, unless you know what's wrong there.

**Comment by sheenaze** [comment]
Ok. If you need help with anything, let me know :)

**Comment by sheenaze** [comment]
I just wanted to say that you seem to be struggling with this one and ask if you need help :)
sure, but tomorrow. I'm calling it a day today.

**Comment by sheenaze** [comment]
Yeah, I know. We need to optimize it somehow.

**Comment by sheenaze** [comment]
@wpreimes if I update pytesmo version to the current master branch (Nico's PR), will it mess up with your PR? Or it should not have any impact?

**Pull request merged**
