### PR TITLE
Added hires to references

### PR DESCRIPTION
**Pull request by pstradio**
Added hires datasets to reference

- [x] Test

### CODE REVIEW

**Comment by pstradio** [comment]
@sheenaze The message:
`The chosen spatial subsetting is bigger than the one covered by chosen datasets. Bounds corrected to fit available subsetting`
Is raised any time one of the two hires datasets is chosed (regardless of the actual selected extent) - and it can be a bit confusing.
I think it has to do with the fact that the condition for the spatial extent is never actually checked in [this part of the code](https://github.com/awst-austria/qa4sm/blob/7ab971aa8aefe5ede56927f564c9f6084b43723e/UI/src/app/pages/validate/validate.component.ts#L486)

**Comment by sheenaze** [comment]
I'm fixing it :)

**Comment by pstradio** [comment]
> I'm fixing it :)

You can push it here

**Comment by sheenaze** [comment]
I opened a PR to your branch :)

**Pull request merged**
