### PR TITLE
User profile editing

### PR DESCRIPTION
**Pull request by bakcsa83**
Implementation of: https://www.awst.at/qa4sm-jira/browse/QA4SM-120

### CODE REVIEW

**Comment by bakcsa83** [comment]
@awst-baum Could you please review?

**Comment by awst-baum** [comment]
Sure, will do after my current tasks, hope to get to it today :)

**Comment by awst-baum** [comment]
It's looking very good!
If find that a very nice way to work :)

What I could spot:

* If I submit two non-matching passwords, I get `"KeyError at /user_profile/ 'password2'"`, the offending line seems to be `validator/forms/user_profile.py:21`
Not quite sure why this happens.

* If I submit two matching passwords, I need to log in again. We should mentally prepare the user for this by mentioning it on the user profile page. "If you change your password, you'll be asked to log in with your new password".

* validator/tests/test_views.py: At the end of test_deactivate_user_profile, try logging in again with the deactivated user and check that you can't.
* Add a test that submits two different passwords and check that the thing you expect to happen happens.

* validator/views/user_profile.py: 
  * Remove print() statement (l17) or replace with logging
  * Remove l29 (return) because the same return happens in l50
  * What does line 40 mean? How can a user be AnonymousUser? If it's possible, add a test that uses the form as such a user. If it shouldn't happen, you can check for it but return a 403 if it happens anyway.

* validator/mailer.py, send_user_account_removal_request: The url should be this instead:
`url = SITE_URL + reverse('admin:validator_user_change', kwargs={'object_id': user.id}),`. Then admins end up on the user edit page, not on the page to activate or deactive the user.

* validator/models/celery_task.py, CeleryTask: Not sure about 'on_delete=models.CASCADE'. This means all related celery_task objects get deleted if a validation is deleted, right? But there should be no celery_task objects if the validation has finished. And if it hasn't finished, then deleting the validation will produce errors, iirc. So a user should first cancel a validation, wait until the tasks have stopped, and then delete the validation. At least that's what I assumed when refactoring the cancellation code.

* Why create `validator/templates/__init__.py`? There should be no python code here?
* Why validator/templates/common/base.html AND validator/templates/validator/base.html? Only one of them should remain?
* I assume the creation of validator/templates/user is because Django expects the user-related templates there?

* Set your Eclipse to spaces only also for HTML files ;-) Window > Preferences > Web > HTML Files > Editor > Idenent using spaces. (I hate Eclipse for this...)

**Comment by bakcsa83** [comment]
@awst-baum 
I've addressed most of the points in the commits above.
Regarding the rest:
> validator/views/user_profile.py:
> Remove l29 (return) because the same return happens in l50
I'm not sure if I understand this one. l29 (now l23) and l50 are not the same.

> I assume the creation of validator/templates/user is because Django expects the user-related templates there?
No. I've created this sub folder for user (and not validation) related stuff. I just didn't want to add user profile files to the validator folder.

**Comment by awst-baum** [comment]
I've merged this after making some more changes myself, mostly to the html pages. You can see them in commit https://github.com/awst-austria/qa4sm/commit/e91846e22f3a172b085d209b4c1972333ef25a2e

**Pull request merged**
