### PR TITLE
adds text to empty validation page

### PR DESCRIPTION
**Pull request by s-scherrer**
Add text to empty validations page and hide sorting form

### CODE REVIEW

**Comment by sheenaze** [comment]
Good idea :)
Please, include if statement entirely in the <form> </form>. Ifs, fors etc, they should not intersect html elements.

**Comment by sheenaze** [comment]
Sorry for being a pain in the neck, but I would do it slightly differently. I would add this code:
`        {% if not myruns %}
        <p class="lead text-muted">
            You have not started any validations yet. Visit the <a href="{% url 'validation' %}">validation page</a>
            to start your own validation run.
        </p>
        {% endif %}
`
in the line 11th (right after "My validations" header) and then removed the further if statement. This way, we will ensure the consistency between this page and  published validations page in terms of the layout.

**Comment by s-scherrer** [comment]
So would you not hide the sorting form if there's nothing to sort?

**Comment by sheenaze** [comment]
If there is nothing, then the page is empty.
Screenshot from 2021-01-14 10-20-37

**Review by sheenaze — APPROVED** [review]

**Pull request merged**
