### PR TITLE
Smos L2 filtering NaNs

### PR DESCRIPTION
**Pull request by pstradio**
This PR comes as a workaround for the fact that 0.0 values in the SMOS L2 data set were reprocessed as NaNs (due to the fillvalue = 0.0). It can be rolled back after a reprocessing of SMOS L2 (after PM6)

### CODE REVIEW

**Comment by pstradio** [comment]
@sheenaze

**Comment by sheenaze** [comment]
@pstradio what do you need from me :)

**Comment by pstradio** [comment]
> @pstradio what do you need from me :)

Just if you could release once I merge it :)

**Comment by sheenaze** [comment]
Just let me know when you merge it :)

**Pull request merged**
