### PR TITLE
Filter updates

### PR DESCRIPTION
**Pull request by wpreimes**
- Added SBPCA Chi2P filter back
- Added new ASCAT version
- A filter can now exclude multiple other filters, not just a single one as before

### CODE REVIEW

**Comment by wpreimes** [comment]
Can be deployed to test. New ascat data is already in place.

**Comment by wpreimes** [comment]
I have update the era5_land metadata now as well. So it will fit to the data that is already on the server and used.

**Comment by wpreimes** [comment]
@sheenaze can you merge and deploy this before the next sprint meeting? Let me know if I should change the target branch to master

**Comment by sheenaze** [comment]
Do we need ESA approval for that? If not, change to master. If not, leave it as it is, I'll take care of it over somehow on the weekend.

**Comment by wpreimes** [comment]
We don't need approval. It's mostly fixes. I will change the branch. Monday or Tuesday is good enough for me ;)

________________________________

**Pull request merged**
