### PR TITLE
Update filters

### PR DESCRIPTION
**Pull request by wpreimes**
- [x] Restoring a validation setup currently raises an error when one of the used filters is not available anymore...should show a warning message in the GUI

### CODE REVIEW

**Comment by wpreimes** [comment]
Added field to filter fixture to activate a filter in the UI by default.

**Comment by sheenaze** [comment]
cna I already merge it and deploy to test?

**Comment by wpreimes** [comment]
> cna I already merge it and deploy to test?

We wanted to implement a warning if not all settings could be restored first, right?

**Comment by sheenaze** [comment]
yes

**Comment by wpreimes** [comment]
Will you do that? Can you push / open a PR to this branch?

**Comment by sheenaze** [comment]
Ok

**Comment by wpreimes** [comment]
@sheenaze should pass now and can be merged from my side

**Comment by sheenaze** [comment]
good. if everything is ok, I'll merge it, deploy it to test today and then do a release next Monday.

**Pull request merged**
