### PR TITLE
Qa4sm 389 ismn dialog window (#80)

### PR DESCRIPTION
**Pull request by sheenaze**
* Revert "updating my fork"

* a bug fixed - default depth values were passed to the database instead of the ones chosen by user

* changed id of a checkbox for parametrized filters and the regular id passed into a hidden field, so that regardless it's disabled filter id is still passed to the database

* label moved before the hidden input, so that styling from css file works properly

* bug fixed: scaling data restored after removal datasets

* necessary filies added

* changed files added

* loading model ISMNNetworks enabled

* improved way of taking dataset name

* Update ismn_dialog.html

toggleISMNContinent function removed from depth selection

Co-authored-by: sheenaze <tercjak@awst>

### CODE REVIEW

**Comment by bakcsa83** [comment]
looks good, go ahead with the merge

**Comment by wpreimes** [comment]
> 
> 
> looks good, go ahead with the merge

can you need to approve otherwise @sheenaze cannot merge (add review)

**Review by bakcsa83 — APPROVED** [review]
looks good, go ahead

**Comment by bakcsa83** [comment]
> > looks good, go ahead with the merge
> 
> @bakcsa83 can you need to approve otherwise @sheenaze cannot merge (add review)
I was not marked as reviewer for this pull request so I could not do that.
Now it should be ok

**Pull request closed without merging**
