### PR TITLE
[QA4SM-275] Add unit to fixtures, model and netcdf file 

### PR DESCRIPTION
**Pull request by wpreimes**

### CODE REVIEW

**Comment by sheenaze** [comment]
@wpreimes: If we want to add it to front end, we need to be clear about the format, but it's not much of work. I'm just wondering if it is not a better idea to do it in the preprocessing package, along with retrieving variable names? Otherwise it's inconsistent @s-scherrer what do you think?

**Comment by wpreimes** [comment]
In principle it's just a string that should go into the data base for the user data. At least the CSV reader should alrady have the information https://github.com/awst-austria/qa4sm-preprocessing/blob/master/src/qa4sm_preprocessing/reading/timeseries.py#L705

**Comment by wpreimes** [comment]
And then we can e.g. show it together with the variable like sm (Soil Moisture) **[m³/m³]**

**Comment by sheenaze** [comment]
You write your comments too fast.

**Comment by sheenaze** [comment]
1. Whatever way we choose, we need to define format of the units to be able to parse them into text properly;
2. if we ask for units in the metadata form but not for the variable itself, it's inconsistent. 
But whatever you prefer.

**Comment by wpreimes** [comment]
1. It's just plain text
2.  I wouldn't ask for units in the metadata form (I assume you mean the my datasets page?). We should take it from the metadata of uploaded files, and only show it on the my dataset page to indicate that a variable has a unit assigned.

**Comment by sheenaze** [comment]
> How to get unit from user upload? Take it from metadata and/or add a field to GUI?

You asked if we should add it to GUI, so I assumed you meant the metadata form. We can derive them from the file I guess, but I'd leave it to @s-scherrer, since he's been working on the preprocessing package, and I can add it to frontend. If there is no value provided I can add a text field for providing the value. Still, whatever we decide, we need to expand our variable model.

**Comment by sheenaze** [comment]
Also, is this issue relevant for release 2?

**Comment by wpreimes** [comment]
ah ok, guess I made up my mind in the meantime then ;) if we don't handle it, I think user data will have units 'unknown' or 'n.a' in the plots.

**Comment by sheenaze** [comment]
Ok, I get the problem now. Yeah, it definitely makes sense to force users to provide units. Can we just require that in the netcdf/csv?

**Comment by sheenaze** [comment]
> Currently, per-variable metadata should already be added to the processed data:
> 
> https://github.com/s-scherrer/qa4sm-preprocessing/blob/f6dbc7d13636d533b030ac1ed5b28bbf5e63b498/tests/test_reading/test_user_upload.py#L110-L112
> 
> I would not enforce the presence of metadata though, since it's only a visual feature. If the users don't want to have nice plots, that's their responsibility, so I would just set it to a default value if it is not provided.

Good point. I agree.

**Pull request merged**
